sort searches on elasticsearch
openlattice/scrunchie pull request #94
Opened 2019-08-21 21:43 UTC by katherinebernstein

2019-08-21 23:37 UTC, you-leee approved these changes

2019-08-21 23:40 UTC, makosblade approved these changes

2019-09-11 00:57 UTC, geekbeast requested changes

2019-09-11 00:57 UTC, geekbeast commented on src/main/java/com/openlattice/kindling/search/ConductorElasticsearchImpl.java
> +            return new EntityDataKeySearchResult( 0, Lists.newArrayList(  ) );
Use the singleton immutable list reference ( i.e ImmutableList.of() )

2019-09-11 00:57 UTC, geekbeast requested changes

2019-09-11 00:57 UTC, geekbeast commented on src/main/java/com/openlattice/kindling/search/ConductorElasticsearchImpl.java
> +            return new EntityDataKeySearchResult( 0, Lists.newArrayList(  ) );
Use the singleton immutable list reference ( i.e ImmutableList.of() )

2019-09-11 00:58 UTC, geekbeast commented
Minor request to use immutable singleton reference for empty replies that will be serialized instead of creating an empty new object.

2019-09-24 21:54 UTC, geekbeast approved these changes

2019-09-24 21:54 UTC, merged